### PR TITLE
testnet: merge dev for relaunch version

### PR DESCRIPTION
**Pull request by MiniFrenchBread**
- Add precompiles and da signers module
- Remove DAS
- Rename denom
- Fix tests

- - -
This change is [Reviewable](https://reviewable.io/reviews/0glabs/0g-chain/28)

### CODE REVIEW

**Comment by zeroxsatoshi** [comment]
*[`client/docs/ibc-go-swagger.yml` line 132 at r1](https://reviewable.io/reviews/0glabs/0g-chain/28#-O-5KGKn-N_qS1c8BM6h:-O-5KGKn-N_qS1c8BM6i:b5l3mfi) ([raw file](https://github.com/0glabs/0g-chain/blob/35a9c8376ebd37d1a3e5c76a33e377f5bb8e4725/client/docs/ibc-go-swagger.yml#L132)):*
> ```YAML
>                     base_denom:
>                       type: string
>                       description: base denomination of the relayed fungible token.
> ```

why change this?

**Review by zeroxsatoshi — CHANGES_REQUESTED** [review]
> Reviewed 135 of 135 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/0glabs/0g-chain/28)* status: all files reviewed, 1 unresolved discussion (waiting on @MiniFrenchBread and @Solovyov1796)

___
*[`migrate/utils/periodic_vesting_reset_test.go` line 44 at r1](https://reviewable.io/reviews/0glabs/0g-chain/28#-O-5Ka1n4AUtpQsKhtA2:-O-5Ka1n4AUtpQsKhtA3:bddzyc0) ([raw file](https://github.com/0glabs/0g-chain/blob/35a9c8376ebd37d1a3e5c76a33e377f5bb8e4725/migrate/utils/periodic_vesting_reset_test.go#L44)):*
> ```Go
> 
> func TestResetPeriodVestingAccount_SingleVestingPeriod_Vested(t *testing.T) {
> 	balance := sdk.NewCoins(sdk.NewCoin("ua0gi", sdkmath.NewInt(1e6)))
> ```

use chaincfg.MakeCoinForGasDenom?

**Comment by Solovyov1796** [comment]
*[`client/docs/ibc-go-swagger.yml` line 132 at r1](https://reviewable.io/reviews/0glabs/0g-chain/28#-O-5KGKn-N_qS1c8BM6h:-O-7QQjO54JxGonLgT_X:brefaqn) ([raw file](https://github.com/0glabs/0g-chain/blob/35a9c8376ebd37d1a3e5c76a33e377f5bb8e4725/client/docs/ibc-go-swagger.yml#L132)):*
<details><summary><i>Previously, zeroxsatoshi (0xsatoshi) wrote…</i></summary><blockquote>

why change this?
</blockquote></details>

I will recover these in another PR.

**Comment by Solovyov1796** [comment]
*[`migrate/utils/periodic_vesting_reset_test.go` line 44 at r1](https://reviewable.io/reviews/0glabs/0g-chain/28#-O-5Ka1n4AUtpQsKhtA2:-O-7QcBlEOIWP-CNKMa_:b-5o5uhv) ([raw file](https://github.com/0glabs/0g-chain/blob/35a9c8376ebd37d1a3e5c76a33e377f5bb8e4725/migrate/utils/periodic_vesting_reset_test.go#L44)):*
<details><summary><i>Previously, zeroxsatoshi (0xsatoshi) wrote…</i></summary><blockquote>

use chaincfg.MakeCoinForGasDenom?
</blockquote></details>

I wiil do this in another PR and merge to testnet/v0.1.x

**Review by zeroxsatoshi — COMMENTED** [review]
> Reviewed 16 of 16 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/0glabs/0g-chain/28)* status: all files reviewed, 1 unresolved discussion (waiting on @MiniFrenchBread)

**Review by zeroxsatoshi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/0glabs/0g-chain/28#-:-O-Kjs0C1U8ARUd4mMAS:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @MiniFrenchBread)

**Pull request merged**
