### PR TITLE
upgrade to kava 26 / cosmos v0.47

### PR DESCRIPTION
**Pull request by 0g-wh**
This change is [Reviewable](https://reviewable.io/reviews/0glabs/0g-chain/52)

### CODE REVIEW

**Comment by Solovyov1796** [comment]
*[`go.mod` line 238 at r1](https://reviewable.io/reviews/0glabs/0g-chain/52#-O3QPQKZEUglRAlvjWAf:-O3QPQK_Dia2b8z3C9-o:b85fe6p) ([raw file](https://github.com/0glabs/0g-chain/blob/932664eface10edd8f51bc4c9fdfa8f1374ba023/go.mod#L238)):*
> ```XML
> 	github.com/ethereum/go-ethereum => github.com/evmos/go-ethereum v1.10.26-evmos-rc2
> 	// Use ethermint fork that respects min-gas-price with NoBaseFee true and london enabled, and includes eip712 support
> 	github.com/evmos/ethermint => github.com/0g-wh/ethermint v0.21.0-0glabs-v26.3.1
> ```

replace with 0glabs' repo

**Comment by Solovyov1796** [comment]
*[`go.mod` line 28 at r1](https://reviewable.io/reviews/0glabs/0g-chain/52#-O3Qr_0YEVS4mQaUTD2X:-O3Qr_0YEVS4mQaUTD2Y:b9wbaev) ([raw file](https://github.com/0glabs/0g-chain/blob/932664eface10edd8f51bc4c9fdfa8f1374ba023/go.mod#L28)):*
> ```XML
> 	github.com/grpc-ecosystem/grpc-gateway v1.16.0
> 	github.com/influxdata/influxdb v1.8.3
> 	github.com/kava-labs/kava v0.26.1
> ```

 should not be referenced

**Comment by Solovyov1796** [comment]
*[`go.mod` line 38 at r1](https://reviewable.io/reviews/0glabs/0g-chain/52#-O3QrkhAD68BApAPHfTf:-O3QrkhB1Nmud0eLtP2v:bg6vozc) ([raw file](https://github.com/0glabs/0g-chain/blob/932664eface10edd8f51bc4c9fdfa8f1374ba023/go.mod#L38)):*
> ```XML
> 	github.com/stretchr/testify v1.8.4
> 	github.com/subosito/gotenv v1.6.0
> 	github.com/tendermint/tendermint v0.35.9
> ```

using cometbft, not tendermint

**Comment by Solovyov1796** [comment]
*[`app/app.go` line 652 at r1](https://reviewable.io/reviews/0glabs/0g-chain/52#-O3QsDqn7M3rNHKkJjXt:-O3QsDqn7M3rNHKkJjXu:bye8f2s) ([raw file](https://github.com/0glabs/0g-chain/blob/932664eface10edd8f51bc4c9fdfa8f1374ba023/app/app.go#L652)):*
> ```Go
> 		evmutil.NewAppModule(app.evmutilKeeper, app.bankKeeper, app.accountKeeper),
> 		// nil InflationCalculationFn, use SDK's default inflation function
> 		mint.NewAppModule(appCodec, app.mintKeeper, app.accountKeeper, nil, mintSubspace),
> ```

missing the chaincfg.NextInflationRate
mint.NewAppModule(appCodec, app.mintKeeper, app.accountKeeper, chaincfg.NextInflationRate, mintSubspace),

**Comment by Solovyov1796** [comment]
*[`cmd/0gchaind/keys.go` line 54 at r1](https://reviewable.io/reviews/0glabs/0g-chain/52#-O3QtXvq69yBDO-S6Q7O:-O3QtXvq69yBDO-S6Q7P:b-2oz04h) ([raw file](https://github.com/0glabs/0g-chain/blob/932664eface10edd8f51bc4c9fdfa8f1374ba023/cmd/0gchaind/keys.go#L54)):*
> ```Go
> 	addCmd := keys.AddKeyCommand()
> 	addCmd.Flags().Bool(ethFlag, false, "use default evm coin-type (60) and key signing algorithm (\"eth_secp256k1\")")
> ```

	algoFlag := addCmd.Flag(flags.FlagKeyType)
	algoFlag.DefValue = string(hd.EthSecp256k1Type)
	err := algoFlag.Value.Set(string(hd.EthSecp256k1Type))
	if err != nil {
		panic(err)
	}

**Comment by Solovyov1796** [comment]
*[`cmd/0gchaind/main.go` line 19 at r1](https://reviewable.io/reviews/0glabs/0g-chain/52#-O3QtiS605Ae4JqiWaI3:-O3QtiS605Ae4JqiWaI4:b2gfhb5) ([raw file](https://github.com/0glabs/0g-chain/blob/932664eface10edd8f51bc4c9fdfa8f1374ba023/cmd/0gchaind/main.go#L19)):*
> ```Go
> 		switch e := err.(type) {
> 		case server.ErrorCode:
> 			fmt.Println("error")
> ```

remove this line

**Comment by 0g-wh** [comment]
> _[`app/app.go` line 652 at r1](https://reviewable.io/reviews/0glabs/0g-chain/52#-O3QsDqn7M3rNHKkJjXt:-O3QsDqn7M3rNHKkJjXu:bye8f2s) ([raw file](https://github.com/0glabs/0g-chain/blob/932664eface10edd8f51bc4c9fdfa8f1374ba023/app/app.go#L652)):_
> 
> > ```go
> > 		evmutil.NewAppModule(app.evmutilKeeper, app.bankKeeper, app.accountKeeper),
> > 		// nil InflationCalculationFn, use SDK's default inflation function
> > 		mint.NewAppModule(appCodec, app.mintKeeper, app.accountKeeper, nil, mintSubspace),
> > ```
> 
> missing the chaincfg.NextInflationRate mint.NewAppModule(appCodec, app.mintKeeper, app.accountKeeper, chaincfg.NextInflationRate, mintSubspace),

the method moved to x/mint/abci.go, chaincfg.NextInflationRate will be deleted later.

**Comment by 0g-wh** [comment]
> _[`cmd/0gchaind/keys.go` line 54 at r1](https://reviewable.io/reviews/0glabs/0g-chain/52#-O3QtXvq69yBDO-S6Q7O:-O3QtXvq69yBDO-S6Q7P:b-2oz04h) ([raw file](https://github.com/0glabs/0g-chain/blob/932664eface10edd8f51bc4c9fdfa8f1374ba023/cmd/0gchaind/keys.go#L54)):_
> 
> > ```go
> > 	addCmd := keys.AddKeyCommand()
> > 	addCmd.Flags().Bool(ethFlag, false, "use default evm coin-type (60) and key signing algorithm (\"eth_secp256k1\")")
> > ```
> 
> ```
> algoFlag := addCmd.Flag(flags.FlagKeyType)
> algoFlag.DefValue = string(hd.EthSecp256k1Type)
> err := algoFlag.Value.Set(string(hd.EthSecp256k1Type))
> if err != nil {
> 	panic(err)
> }
> ```

why we need this? check https://github.com/Kava-Labs/kava/blob/v0.26.0/cmd/kava/cmd/keys.go#L53

**Comment by Solovyov1796** [comment]
*[`cmd/0gchaind/keys.go` line 54 at r1](https://reviewable.io/reviews/0glabs/0g-chain/52#-O3QtXvq69yBDO-S6Q7O:-O3QzZA66CYTtM-c2_lu:be4047) ([raw file](https://github.com/0glabs/0g-chain/blob/932664eface10edd8f51bc4c9fdfa8f1374ba023/cmd/0gchaind/keys.go#L54)):*
<details><summary><i>Previously, 0g-wh wrote…</i></summary><blockquote>

why we need this? check https://github.com/Kava-Labs/kava/blob/v0.26.0/cmd/kava/cmd/keys.go#L53
</blockquote></details>

default using EthSecp256k1Type when keys add without --eth

**Review by Solovyov1796 — APPROVED** [review]
> Reviewed 1086 of 1086 files at r1, 12 of 12 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/0glabs/0g-chain/52)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @0g-wh)

**Pull request merged**
